[package]
name = "yubikey-watcher"
version = "0.1.0"
authors = ["Simon Strassl <simon@sigmoid.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4"
clap = "2.33.0"
log = "0.4.8"
env_logger = "0.7.1"
regex = "1"